// export {default as MyComponent} from './base/MyComponent'
export {default as Text} from './Text'
export {default as Image} from './Image'
export {default as ImageWithLinks} from './ImageWithLinks'
export {default as TextWithImage} from './TextWithImage'
export {default as HomepageRecommendations} from './HomepageRecommendations'
export {default as HomepageBrandGallery} from './HomepageBrandGallery'
export {default as Banner} from './Banner'
export {default as MagazineArticleTeaserByIdWidget} from './MagazineArticleTeaserByIdWidget'
export {default as Squarelovin} from './Squarelovin'
export {default as CurratedSearchWidget} from './CurratedSearchWidget'