// @flow

export const ADD_ITEM_REQUEST:'cart/ADD_ITEM_REQUEST' = 'cart/ADD_ITEM_REQUEST'
export const ADD_ITEM_SUCCESS:'cart/ADD_ITEM_SUCCESS' = 'cart/ADD_ITEM_SUCCESS'
export const ADD_ITEM_FAILURE:'cart/ADD_ITEM_FAILURE' = 'cart/ADD_ITEM_FAILURE'
export const FETCH_CART_REQUEST:'cart/FETCH_CART_REQUEST' = 'cart/FETCH_CART_REQUEST'
export const FETCH_CART_SUCCESS:'cart/FETCH_CART_SUCCESS' = 'cart/FETCH_CART_SUCCESS'
export const FETCH_CART_FAILURE:'cart/FETCH_CART_FAILURE' = 'cart/FETCH_CART_FAILURE'